server:
  port: 8080
  address: 0.0.0.0

internal:
  server:
    port: 8082

spring:

  jackson:
    time-zone: UTC
    deserialization:
      accept_empty_string_as_null_object: true

  application:
    name: arka

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

jwt-provider:
  secret: ${JWT_SECRET}

cloud-provider:
  aws:
    s3:
      bucket-name: ${BUCKET_NAME}
      templates:
        html-template-order-state-email: ${S3_KEY_HTML_TEMPLATE_ORDER_STATE_EMAIL}
    ses:
      sender: ${SES_SENDER_EMAIL}


springdoc:
  swagger-ui:
    urls:
      - name: 'auth-service'
        url: "${AUTH_SERVICE_BASE_URL:}/v3/api-docs/auth-api"
      - name: 'public-api'
        url: '/v3/api-docs/public-api'
      - name: 'internal-api'
        url: '/v3/api-docs/internal-api'
    path: "/swagger-ui.html"
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    default-models-expand-depth: -1
    default-group: public-api
    groups-order: DESC
  api-docs:
    path: /v3/api-docs

api:
  base-url: ${API_BASE_URL}
