pluginManagement {
    repositories {
        gradlePluginPortal()
    }
}

rootProject.name = 'back-arka-core'

include(":boot",
        ":model",
        ":jpa-repository",
        ":usecase",
        ":api-rest",
        ":security",
        ":export-data",
        ":aws-provider",
        ":sqs-listener"
)

project(":boot").projectDir = file("./main-app/boot")
project(":model").projectDir = file("./domain/model")
project(":usecase").projectDir = file("./domain/usecase")
project(":jpa-repository").projectDir = file("./infrastructure/driven-adapters/jpa-repository")
project(":export-data").projectDir = file("./infrastructure/driven-adapters/export-data")
project(":api-rest").projectDir = file("./infrastructure/entry-points/api-rest")
project(":sqs-listener").projectDir = file("./infrastructure/entry-points/sqs-listener")
project(":security").projectDir = file("./infrastructure/entry-points/security")
project(":aws-provider").projectDir = file("./infrastructure/driven-adapters/aws-provider")

