dependencies {
    implementation project(":model")
    implementation project(":usecase")
    implementation project(":security")

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.15")
    implementation 'org.springframework.data:spring-data-commons'

    // Spring DAO exceptions (DataIntegrityViolationException, etc.)
    implementation 'org.springframework:spring-tx'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly files("${project(':boot').projectDir}/src/main/resources")
}

//config to resolve SQL native query parameters
tasks.withType(JavaCompile).configureEach {
    options.compilerArgs << '-parameters'
}
